### ISSUE TITLE
List of features for frontend

### ISSUE THREAD

**Issue by sksuryan** [AhadKhan98/Flyrics#6]
- [x] Create a basic UI for the React Native App with UI components for recording audio and uploading files #1 

- [x] Ability to record audio #2 

- [x] Ability to upload recorded audio and audio files from device #3 

- [x] UI to show lyrics
